apiVersion: v1
kind: Template
labels:
  template: component1-builder
metadata:
  annotations:
    description: component1 container
    iconClass: component1
    tags: instant-app
  name: component1-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
    name: component1
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: component1
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: component1:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: CONTAINER_NAME
            value: component1
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/scoheb/containerCIDemo.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: config/component1
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master
